data_domain: graph
data_type: Transactions
data_name: AragonNetwork
data_dir: datasets/${data_domain}/${data_type}

num_features: 1
num_classes: 1
task: classification
loss_type: cross_entropy
task_level: graph